import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./styles/pdfStyles";
// Import asset CSS so the web build includes the stylesheet as a reference
import "./assets/stylesheet/pdfStyles.css";
import FIELDS from "../../shared/filefield.json";

export default function SacPdf({ values }) {
  const safeValues = values || {};

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.headerLine} />
        <Text style={styles.title}>SAC Instruction Sheet</Text>
        <Text style={styles.subtitle}>Advanced Image Analysis Report</Text>
        <View style={styles.divider} />

        {/* Render fields in canonical order from shared/filefield.json */}
        {FIELDS.map((f, idx) => {
          const key = f.key;
          const label = f.label || key;
          const val = safeValues[key] !== undefined && safeValues[key] !== null && safeValues[key] !== ""
            ? String(safeValues[key])
            : "—";

          return (
            <View key={key} style={[styles.row, idx % 2 === 0 && styles.rowEven]}>
              <Text style={styles.key}>{label}</Text>
              <Text style={styles.val}>{val}</Text>
            </View>
          );
        })}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by SAC Image Analysis System | 2026</Text>
        </View>
      </Page>
    </Document>
  );
}
